from executive_coach.prompts.coordinator import COORDINATOR_PROMPT
from executive_coach.prompts.accountability import ACCOUNTABILITY_PROMPT
from executive_coach.prompts.decision import DECISION_PROMPT
from executive_coach.prompts.career_coach import CAREER_COACH_PROMPT
